default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  pool: 5

development:
  <<: *default
  database: hotwire_react_development

test:
  <<: *default
  database: hotwire_react_test

production:
  <<: *default
  database: hotwire_react_production
  username: hotwire_react
  password: <%= ENV['HOTWIRE_REACT_DATABASE_PASSWORD'] %>

