default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %> # This should match the service name in your docker-compose.yml

development:
  <<: *default
  database: hotwire_react_development

test:
  <<: *default
  database: hotwire_react_test

production:
  <<: *default
  database: hotwire_react_production
  username: <%= ENV['HOTWIRE_REACT_DATABASE_USER'] %>
  password: <%= ENV['HOTWIRE_REACT_DATABASE_PASSWORD'] %>
